CREATE TABLE job {
  id BIGSERIAL PRIMARY KEY NOT NULL,
  title: VARCHAR(80) NOT NULL,
}

CREATE TABLE employer {
  id BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(80) NOT NULL,
  degree VARCHAR(20) NOT NULL,
  salary VARCHAR(20) NOT NULL,
  job_id BIGINT REFERENCES job(id),
}